config/routes.rb
Rails.application.routes.draw do
  resources :orders
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'orders#index'
  put '/orders/submit/:id/', to: 'orders#submit', as: 'submit'
  put '/orders/cancel/:id/', to: 'orders#cancel', as: 'cancel'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :line_items
  has_many :products, through: :line_items
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :submit, :cancel]
  
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @customers = Customer.all
    @products = Product.all
  end

  # GET /orders/1/edit
  def edit
    @customers = Customer.all
    @products = Product.all
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(:customer_id => order_params[:customer_id])

    order_params[:line_items].each do |item|
      if !item.empty?
        @order.line_items.new(:product_id => item, :order_id => @order.id)
        @order.update(cost: @order.cost + @order.line_items[0].product.price)
      end
    end

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    @order.line_items.destroy_all
    @order.update(cost: 0)

    order_params[:line_items].each do |item|
      if !item.empty?
        @order.line_items.create(:product_id => item, :order_id => @order.id)
        @order.update(cost: @order.cost + @order.line_items[0].product.price)
      end
    end

    respond_to do |format|
      format.html { redirect_to @order, notice: 'Order was successfully updated.' }
      format.json { render :show, status: :ok, location: @order }
    end
  end

  def submit
    if (@order.line_items.length == 0)
      respond_to do |format|
        format.html { redirect_to orders_path, notice: 'Cannot submit empty order.' }
        format.json { render :show, status: :ok, location: orders_path }
      end
      return
    end

    @order.update(submitted: true)

    respond_to do |format|
      format.html { redirect_to orders_path, notice: 'Order was successfully updated.' }
      format.json { render :show, status: :ok, location: orders_path }
    end
  end

  def cancel
    @order.update(canceled: true)

    respond_to do |format|
      format.html { redirect_to orders_path, notice: 'Order was successfully updated.' }
      format.json { render :show, status: :ok, location: orders_path }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OllieOrderForm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class='container'>
    <%= yield %>
  </div>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <div class='field'>
    <%= form.label :customer %>
    <%= form.select :customer_id, options_for_select(@customers.collect{ | customer | [customer.name, customer.id] }) %>
  </div>

  <div class='field'>
    <%= form.label :product %>
    <%= form.select :line_items, options_for_select(@products.collect {| product | [ product.name, product.id ] }), { :options => {}}, multiple: true, size: @products.length %>
  </div>

  <div class='actions'>
    <%= form.submit('Create Order') %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1 class='order_title'>Editing Order</h1>

<%= render 'form', order: @order %>

<div class='links'>
  <%= link_to 'Show', @order %> |
  <%= link_to 'Back', orders_path %>
</div>

app/views/orders/index.html.erb
<p id='notice'><%= notice %></p>

<h1 class='order_title'>Orders</h1>

<table class='table_index'>
  <thead>
    <tr>
      <th>Order #</th>
      <th>Customer</th>
      <th>Product</th>
      <th>Sub-total</th>
      <th>Total</th>
      <th>Status</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.customer.name %></td>
        <td>
          <% order.products.each do |product| %>
            <% if order.products.last.equal?(product) %>
              <%= product.name %>
            <% else %>
              <%= product.name %>,
            <% end %>
          <% end %>
        </td>
        <td>$<%= order.cost %></td>
        <td>$<%= order.cost + order.cost * 0.15 %></td>
        <% if order.canceled %>
          <td><%= 'CANCELED' %></td>
        <% else %>
          <td><%= order.submitted ? 'SUBMITTED' : 'DRAFT' %></td>
        <% end %>
        <div class='links'>
          <td><%= link_to 'Show', order %></td>
          <% if !order.submitted && !order.canceled %>
            <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Submit', submit_path(order.id), method: 'put' %></td>
            <td><%= link_to 'Cancel', cancel_path(order.id), method: 'put' %></td>
          <% end %>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class='links'>
  <%= link_to 'New Order', new_order_path %>
</div>

app/views/orders/new.html.erb
<h1 class='order_title'>New Order</h1>

<%= render 'form', order: @order %>

<div class ='links'>
  <%= link_to 'Back', orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<div class="field">
  <p>
    <strong>Customer:</strong>
    <%= @order.customer.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @order.submitted ? 'SUBMITTED' : 'DRAFT' %>
  </p>

  <p>
    <strong>Product:</strong>
    <% @order.products.each do | product | %>
      <div>
        <%= product.name %>
      </div>
    <% end %>
  </p>

  <p>
    <strong>Sub-total:</strong>
    <div>$<%= @order.cost %></div>
  </p>

    <p>
    <strong>Total:</strong>
    <div>$<%= @order.cost + @order.cost * 0.15 %></div>
  </p>
</div>

<div class='links'>
  <% if !@order.submitted %>
    <%= link_to 'Edit', edit_order_path(@order) %> |
  <% end %>
  <%= link_to 'Back', orders_path %>
</div>